stock_groups= { 
    'LI':(
        'MMM5',
        'ROSN',
        'MAGN',
        'CHMF',
        'NVTK',
        'ALRS',
        'SELG',
        'TATN',
        'RUAL',
        'MTLR',
        'VTBR',
        'GMKN'
    ),
    'TS': (
        'CHMF',
        'NVTK',
        'CBOM',
        'LSRG',
        'FESH',
        'MAGN',
        'NLMK',
        'HYDR',
        'VTBR',
        'IRAO',
        'PIKK',
        'MTLR'
    )
}
