tickersMoexFut = (
    ('CRM5',True),
    ('MMM5',True),
    ('MXM5',True),
    ('GZM5',True),
    ('SRM5',True),
    ('RIM5',True),
    ('RMM5',True),
    ('SiM5',True),
    ('IMOEXF',True),
    ('CNYRUBF',True),
)

tickersMoexStock = (
    ('SBER',False),
    ('GAZP',False),
    ('LKOH',False),
    ('ROSN',False),
    ('MTLR',False),
    ('MGNT',False),
    ('NVTK',False),
    ('GMKN',False),
    ('VTBR',False),
    ('TATN',False),
    ('TRNFP',False),
    ('AFKS',False),
    ('PIKK',False),
    ('MOEX',False),
    ('AFLT',False),
    ('CHMF',False),
    ('NLMK',False),
    ('SIBN',False),
    ('SNGSP',False),
    ('SNGS',False),
    ('ALRS',False),
    ('MAGN',False),
    ('MTSS',False),
    ('RUAL',False),
    ('FESH',False),
    ('IRAO',False),
    ('RTKM',False),
    ('UPRO',False),
    ('FEES',False),
    ('BANEP',False),
    ('TRMK',False),
    ('LSRG',False),
    ('CBOM',False),
    ('NMTP',False),
    ('HYDR',False),
    ('SELG',False),
    ('YDEX',False),
)

tickersBitgetFut = (
    ("DOGEUSDT",True),
)